---
title: "Creating Slides in Quarto"
author: Joy Payton
format: revealjs
editor: visual
---

## Today's Itinerary:

* Do some setup to allow for publishing your slides online
* Create some boring slides 
* Publish boring slides
* Make more interesting slides
* Publish, rinse, repeat.

## Quarto

* Quarto ≈ R Markdown.  
* We'll use RStudio to write Quarto.
* <https://quarto.org/docs/presentations/>

## GitHub

We'll be using GitHub (<https://github.com>) to make a published slide deck. There are other ways to publish your slides, but this might be the easiest, and requires no additional account setups.

GitHub offers **version control**.

## GitHub

New to GitHub?  You can sign up for free! <https://github.com> 

You will also want to install git on your local computer and have a GitHub client like GitHub Desktop installed as well.

## Create a New Repository

* Create a new repository in GitHub, and clone it to your desktop.
* Make a new folder called "docs" within your repo -- this is where your online slides / website will live.

## Create a New R Project 

* Create a new R Project in an existing directory (the one you just set up)
* Open in new Session

## Create a New Quarto Presentation

* File > New > Quarto Presentation
* Change any yml you want at the top
* Save it with a useful name (`index.qmd` is particularly good)
* Render and take a peek!

## Add Support Files

* Add a `.gitignore` with `.Rproj*/*` and (if on a Mac) `.DS_Store`
* Add an empty file called `.nojekyll`

## Push to GitHub

* Push changes to GitHub
* Make GitHub Pages changes ("docs", main)

## Improve your slides with R / Markdown

* Add formatting
* Add code (example: countdown timer!)
* Add images

## Add special stuff

Quarto-specific:

* Speaker notes
* Layout
* Themes



